services:
  streamlit:
    image: vinitjava/my-ai-learning:streamlit
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501

  flask:
    image: vinitjava/my-ai-learning:flask
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONHTTPSVERIFY=0
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

  backend:
    image: vinitjava/my-ai-learning:backend
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local